### ISSUE TITLE
希望能添加点击跳转相应页数的方法。

### ISSUE THREAD

**Issue by Ohuisang** [an0/WLPageViewController#3]
先谢过~ 这里只是提个意见~
项目需求做阅读方面的功能，用了官方的UIPageController 滚动方法，实现页面加载有问题。所以 使用WLPageViewController 可以正常使用。在使用过程中发现两个问题：
1.一个问题是 没有点击跳转的方式，自己在源码上加了个方法实现。
2.是导航栏子标题有问题，title没有值的时候会奔溃。

```
- (UIView *)setupSubTitleViewWith:(UIViewController *)viewController {

     //--- 修改后
     titleLabel.attributedText = [[NSAttributedString alloc] initWithString:viewController.navigationItem.title?:@"" attributes:_titleTextAttributes];

     //---
}
```

**Comment by an0** [comment]
1. enableTapPageTurning
2. 这个组件的起因就是“synchronous navigation title transition support”，没有 title 没有意义。

**Comment by Ohuisang** [comment]
感谢回复~ 可能我没说清楚我的意思
1. enableTapPageTurning 只是点击跳转相邻两个页面，我的意思是手动跳转任意页面，例如，当前页为第一页，跳转至第五页。
2. 了解了~ 但是感觉可能判断下空值避免奔溃会好些。因为 demo 中也没提现出 “synchronous navigation title transition support” 这个特性，然后我就只是仅仅把它单做 UIPageController 的替代使用，导致崩溃。

我关于 title 的理解，不知道有没有理解错，如果有错希望点出：

看了代码中最终设置的是 WLPageViewController.navigationItem.titleView，但是 WLPageViewController 使用的时候是被添加到父视图控制器上的。那只改变 WLPageViewController.navigationItem.titleView 的话，父视图控制器上的 titleView 并不会改变吧。

使用过程中我设置内容页 title，也只是避免了奔溃，视图控制器上的 title 也并没有改变。 

然后我尝试修改了WLPageViewController.m 文件中的 self.navigationItem 为 self.parentViewController.navigationItem。“synchronous navigation title transition support” 是会体现出来（虽然第一次加载 titleView 时位置会发生偏移）。

不知是不是作者写的时候是 iOS5，后面实现方式有变化造成的。

**Comment by an0** [comment]
1. PageViewController 的数据模型是序列的不是 indexed。
2. 见主页说明。不需要这个特性的话直接用 UIPageViewController 就好了，用 WLPageViewController 没有意义。
3. 你可以任意根据自己需求改代码，这是开源的意义所在。

**Comment by Ohuisang** [comment]
嗯😂 还是感谢回复吧。顺带一句：moke 客户端除开借口限制，还是很好用的:-)

**Comment by an0** [comment]
谢谢😄
